spring.application.name=server
logging.level.org.springframework=info
spring.main.allow-bean-definition-overriding=true
server.servlet.context-path=/
spring.web.error.include-message=always
server.port=8080

spring.ai.openai.enabled=false
spring.ai.openai.api-key=${API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=meta-llama/llama-4-scout-17b-16e-instruct

spring.ai.openai.chat.options.stream-usage=false
spring.ai.openai.chat.options.store=false

spring.data.mongodb.uri=${DATASOURCE_URL}
spring.data.mongodb.database=audit

spring.jackson.mapper.default-view-inclusion=true
spring.jackson.deserialization.fail-on-unknown-properties=false