spring.application.name=server
logging.level.org.springframework=info
spring.main.allow-bean-definition-overriding=true
server.servlet.context-path=/
spring.web.error.include-message=always
server.port=8080

spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=meta-llama/llama-4-scout-17b-16e-instruct

spring.data.mongodb.uri=mongodb+srv://root:root@cluster0.bfsbxsg.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=audit